### ISSUE TITLE
cURL and billing_email property errors prevent the order sync to MC

### ISSUE THREAD

**Issue by 0ngar** [ibericode/mailchimp-for-wordpress#537]
My website URL: www.angolodeldiabetico.it

Dear ibericode community, my console log shows the following error messages:

- [2018-02-24 12:14:54] ERROR: E-Commerce: Customer data requires a billing_email property
- [2018-02-24 12:56:45] ERROR: E-Commerce: Error adding order #9286. cURL error 28: Operation timed out after 10002 milliseconds with 0 bytes received.

These prevent orders and customers data to be passed to MailChimp and queued background jobs number is growing every day. Can anyone help me to overcome the issue?
Best,
Antonello
### How can we reproduce this issue?
1. Customer make an order (Woocommerce)
2. The order data is passed to MC

### Technical info
* WordPress version: 4.9.4
* MailChimp for WordPress version: Version 4.1.15 and Premium Version 3.3.27
* Relevant plugins in case of a bug: Woocommerce, Woocommerce product bundle, Betheme (customized), W3 Total Cache

**Comment by 0ngar** [comment]
The curl problem seems to be solved by itself. The second one, regarding the missing billing email field, is still present. Can anybody help me to debug it? Best regards,
Anto

**Comment by dannyvankooten** [comment]
Hi @0ngar,

The missing billing_email field depends on your WooCommerce configuration, as by default all customers should have this field. Do you allow your customers to place orders without providing a valid email address? Or do you perhaps store your email addresses in a different field than the "billing_email" property?

Also, what version of WooCommerce are you on?

**Comment by 0ngar** [comment]
Dear @dannyvankooten thanks for your reply. To reply to your question I can state that a user can't proceed to checkout without a valid email. Moreover, the field "billing_email" is stored within the "usermeta" table and, checking the DB, it seems to be correctly populated. I'm using WP 4.9.4 and I've no clued why this glitch happens.

**Comment by dannyvankooten** [comment]
Hey @0ngar, thanks for the additional details. And what version of WooCommerce are you running?

**Comment by 0ngar** [comment]
@dannyvankooten WC 3.3.3. I'm using some plugin to customize the WC experience but no one of these will compromise the billing_email field. Do you need the complete list of the extensions?

**Comment by dannyvankooten** [comment]
Hey @0ngar, I believe I know what is causing this. Will hopefully be fixed in the next plugin update!

**Comment by 0ngar** [comment]
@dannyvankooten amazing man. You save my day. There is an ETA about? Meanwhile, I can bu sure about the email and meta sync through the MC plugin? Best regards!

**Comment by dannyvankooten** [comment]
Hi @0ngar, version 3.3.28 was released about an hour ago, it should include the fix. Let me know if it doesn't please!

**Comment by 0ngar** [comment]
@dannyvankooten It seems to be ok; by now the log is clear. The patch will solve even the curl glitch?

**Comment by 0ngar** [comment]
@dannyvankooten the log still present an error report (not regarding billing email but curl):

[2018-02-27 11:25:25] ERROR: E-Commerce: Error adding order #9295. cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received.

Can you help me again please?

**Comment by dannyvankooten** [comment]
Hi @0ngar,

Unfortunately, that error is something the plugin can't do much about as it is happening on a network level, and not on a software level. It could have various reasons, eg MailChimp temporarily firewalling you because of making too many requests or perhaps your PHP CURL software is outdated.

How many orders & products do you have? Does the issue occur after attempting to send many of them to MailChimp?

**Comment by 0ngar** [comment]
@dannyvankooten I understand what you suppose but... when the alert was logged (11:25) the order count was 0...
